apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: catalog
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-07a24c02be9df7a92"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-095f67ced7685793a"
spec:
  type: LoadBalancer
  selector:
    app: catalog-service
  ports:
    - port: 80
      targetPort: 9001
